"""add declined_creators table

Revision ID: 2a7359f2c90f
Revises: add_conservative_click_estimate
Create Date: 2025-10-09 16:39:59.200791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7359f2c90f'
down_revision: Union[str, Sequence[str], None] = 'add_conservative_click_estimate'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declined_creators',
    sa.Column('declined_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('declined_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint('creator_id != advertiser_id', name='check_creator_not_advertiser'),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.advertiser_id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.creator_id'], ),
    sa.PrimaryKeyConstraint('declined_id')
    )
    op.create_index(op.f('ix_declined_creators_declined_id'), 'declined_creators', ['declined_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_declined_creators_declined_id'), table_name='declined_creators')
    op.drop_table('declined_creators')
    # ### end Alembic commands ###
