"""add conservative_click_estimate to creators

Revision ID: add_conservative_click_estimate
Revises: b89794560fae
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_conservative_click_estimate'
down_revision = 'b89794560fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('conservative_click_estimate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creators', 'conservative_click_estimate')
    # ### end Alembic commands ###
